### ISSUE TITLE
Boards Manager installation of 2.8.1 release fails due to unsupported platform archive structure

### ISSUE THREAD

**Issue by per1234** [Seeed-Studio/ArduinoCore-mbed#14]
The platform archive for the 2.8.1 release has an unsupported structure. This causes installation to fail when using the [Arduino IDE 2.x](https://github.com/arduino/arduino-ide) or [**Arduino CLI**](https://arduino.github.io/arduino-cli/latest/) Boards Manager:

```text
Failed to install platform: Seeeduino:mbed.
Error: 13 INTERNAL: Cannot install platform: installing platform Seeeduino:mbed@2.8.1: searching package root dir: no unique root dir in archive, found 'C:\Users\per\AppData\Local\Arduino15\tmp\package-3860729226\.github' and 'C:\Users\per\AppData\Local\Arduino15\tmp\package-3860729226\bootloaders'
```

As indicated by the error, the problem is there is no root folder in the archive:

https://files.seeedstudio.com/arduino/core/mbed/ArduinoCore-mbed-Seeed-2.8.1.tar.gz

```text
.
├── README.md
├── bfg_nano33ble.sh
├── boards.txt
├── bootloaders/
├── cores/
├── drivers/
├── edge.variables
├── extras/
├── full.variables
├── libraries/
├── mbed-os-to-arduino
├── mbed_lib.json
├── nano.variables
├── nicla.variables
├── package.sh
├── package_full.sh
├── patches/
├── platform.txt
├── portenta.variables
├── post_install.bat*
├── post_install.sh
├── programmers.txt
├── rp2040.variables
├── sketches-reports/
├── tools/
└── variants/
```

The platform archive of the 2.7.2 release has the correct structure:

https://files.seeedstudio.com/arduino/core/mbed/20220720_XIAOBLE_2.7.2.tar.bz2

```text
.
└── 2.7.2/
    ├── README.md
    ├── bfg_nano33ble.sh
    ├── boards.txt
    ├── bootloaders/
    ├── cores/
    ├── drivers/
    ├── edge.variables
    ├── extras/
    ├── full.variables
    ├── libraries/
    ├── mbed-os-to-arduino
    ├── mbed_lib.json
    ├── nano.variables
    ├── nicla.variables
    ├── package.sh
    ├── package_full.sh
    ├── patches/
    ├── platform.txt
    ├── portenta.variables
    ├── post_install.bat*
    ├── post_install.sh
    ├── programmers.txt
    ├── rp2040.variables
    ├── tools/
    └── variants/
```

---

Originally reported at:

- https://forum.seeedstudio.com/t/xiao-ble-sense-cannot-communicate-with-imu-sensor/265629/21
- https://forum.arduino.cc/t/unable-to-install-seeed-nrf52-mbed-enabled-boards-2-8-1-on-ide-2-0-3/1071053

**Comment by LynnL4** [comment]
Thanks,  slove in (https://github.com/Seeed-Studio/ArduinoCore-mbed/commit/58f91746d2a1cabdb5cd118ae4cd984448c358ba)
