### ISSUE TITLE
XIAO Sense api used on wiki missing, was in the primo core and not replaced

### ISSUE THREAD

**Issue by ohsix** [Seeed-Studio/ArduinoCore-mbed#15]
https://github.com/Seeed-Studio/wiki-documents/issues/9

an example from a similar core to the seeed nrf52 core (not the mbed one) is here https://github.com/0hotpotman0/BLE_52840_Core/tree/main/libraries/nfc

i got these based on the wiki saying nfc worked

**Comment by Maxwelltoo** [comment]
nfc library has been added in v2.9.2
